export const SUPPORTED_CHAINS = [
  'ethereum',
  'bsc',
  'polygon',
  'arbitrum',
  'base',
  'optimism',
  'avalanche',
  'abstract',
  'apechain',
  'berachain',
  'bittorrent',
  'blast',
  'celo',
  'fraxtal',
  'gnosis',
  'hyperevm',
  'katana',
  'linea',
  'mantle',
  'megaeth',
  'memecore',
  'monad',
  'moonbeam',
  'moonriver',
  'opbnb',
  'plasma',
  'sei',
  'sonic',
  'stable',
  'taiko',
  'unichain',
  'world',
  'xdc',
] as const;

export type Chain = (typeof SUPPORTED_CHAINS)[number];

// All chain IDs verified live against https://api.etherscan.io/v2/chainlist
// and cross-matched to CoinGecko asset platforms via chain_identifier.
export const ETHERSCAN_CHAIN_IDS: Record<Chain, number> = {
  ethereum: 1,
  bsc: 56,
  polygon: 137,
  arbitrum: 42161,
  base: 8453,
  optimism: 10,
  avalanche: 43114,
  abstract: 2741,
  apechain: 33139,
  berachain: 80094,
  bittorrent: 199,
  blast: 81457,
  celo: 42220,
  fraxtal: 252,
  gnosis: 100,
  hyperevm: 999,
  katana: 747474,
  linea: 59144,
  mantle: 5000,
  megaeth: 4326,
  memecore: 4352,
  monad: 143,
  moonbeam: 1284,
  moonriver: 1285,
  opbnb: 204,
  plasma: 9745,
  sei: 1329,
  sonic: 146,
  stable: 988,
  taiko: 167000,
  unichain: 130,
  world: 480,
  xdc: 50,
};

// CoinGecko "asset platform" ids, for the /simple/token_price/{platform} endpoint.
export const COINGECKO_PLATFORM_IDS: Record<Chain, string> = {
  ethereum: 'ethereum',
  bsc: 'binance-smart-chain',
  polygon: 'polygon-pos',
  arbitrum: 'arbitrum-one',
  base: 'base',
  optimism: 'optimistic-ethereum',
  avalanche: 'avalanche',
  abstract: 'abstract',
  apechain: 'apechain',
  berachain: 'berachain',
  bittorrent: 'bittorrent',
  blast: 'blast',
  celo: 'celo',
  fraxtal: 'fraxtal',
  gnosis: 'xdai',
  hyperevm: 'hyperevm',
  katana: 'katana',
  linea: 'linea',
  mantle: 'mantle',
  megaeth: 'megaeth',
  memecore: 'memecore',
  monad: 'monad',
  moonbeam: 'moonbeam',
  moonriver: 'moonriver',
  opbnb: 'opbnb',
  plasma: 'plasma',
  sei: 'sei-v2',
  sonic: 'sonic',
  stable: 'stable',
  taiko: 'taiko',
  unichain: 'unichain',
  world: 'world-chain',
  xdc: 'xdc-network',
};

// CoinGecko coin ids for each chain's native gas token (many L2s settle in ETH).
export const NATIVE_COINGECKO_IDS: Record<Chain, string> = {
  ethereum: 'ethereum',
  bsc: 'binancecoin',
  polygon: 'polygon-ecosystem-token',
  arbitrum: 'ethereum',
  base: 'ethereum',
  optimism: 'ethereum',
  avalanche: 'avalanche-2',
  abstract: 'ethereum',
  apechain: 'apecoin',
  berachain: 'berachain-bera',
  bittorrent: 'bittorrent',
  blast: 'ethereum',
  celo: 'celo',
  fraxtal: 'frax-share',
  gnosis: 'xdai',
  hyperevm: 'hyperliquid',
  katana: 'ethereum',
  linea: 'ethereum',
  mantle: 'mantle',
  megaeth: 'ethereum',
  memecore: 'memecore',
  monad: 'monad',
  moonbeam: 'moonbeam',
  moonriver: 'moonriver',
  opbnb: 'binancecoin',
  plasma: 'plasma',
  sei: 'wrapped-sei',
  sonic: 'sonic-3',
  stable: 'usdt0',
  taiko: 'ethereum',
  unichain: 'ethereum',
  world: 'ethereum',
  xdc: 'xdce-crowd-sale',
};

export const NATIVE_SYMBOLS: Record<Chain, string> = {
  ethereum: 'ETH',
  bsc: 'BNB',
  polygon: 'POL',
  arbitrum: 'ETH',
  base: 'ETH',
  optimism: 'ETH',
  avalanche: 'AVAX',
  abstract: 'ETH',
  apechain: 'APE',
  berachain: 'BERA',
  bittorrent: 'BTT',
  blast: 'ETH',
  celo: 'CELO',
  fraxtal: 'FRAX',
  gnosis: 'XDAI',
  hyperevm: 'HYPE',
  katana: 'ETH',
  linea: 'ETH',
  mantle: 'MNT',
  megaeth: 'ETH',
  memecore: 'M',
  monad: 'MON',
  moonbeam: 'GLMR',
  moonriver: 'MOVR',
  opbnb: 'BNB',
  plasma: 'XPL',
  sei: 'WSEI',
  sonic: 'S',
  stable: 'USDT0',
  taiko: 'ETH',
  unichain: 'ETH',
  world: 'ETH',
  xdc: 'XDC',
};
